### ISSUE TITLE
X.0em

### ISSUE THREAD

**Issue by aaron-bru** [matthiassiegel/cssminify#1]
Hi, just starting using this, thanks for a great library!
Had an inconsistency on a project after parsing, noticed it was a result of rule
font-size: 2.0em;
missing after minification. Changing it to 2em fixed it. (other X.Yem rules were fine)
Not sure what spec is, but probably would be good to support that. I installed from rubygems

**Comment by matthiassiegel** [comment]
Project is no longer maintained, sorry. Feel free to fork.
