### ISSUE TITLE
Breaks calc()

### ISSUE THREAD

**Issue by elliotdickison** [matthiassiegel/cssminify#2]
It appears that this is removing the whitespace between the terms and operators in calc() expressions, which results in broken css. For example, `padding-left: calc(75px + 1em);` is being minified as `padding-left: calc(75px+1em);`, which is invalid and won't work.

**Comment by matthiassiegel** [comment]
Project is no longer maintained, sorry. Feel free to fork.

If you're using SASS, I suggest using compress mode, and then gzip compression on your web server. Much better results.

**Comment by elliotdickison** [comment]
Ah, well thanks for the suggestion!

**Comment by jcward** [comment]
Hmm, I might leave issues like this open, then. Closing issues as "unmaintained" seems a little disingenuous... Because people see a "0" next to the issues tab and get a false sense of security.
